@startuml

title __USERDEVELOPMENT's Class Diagram__\n

  namespace com.example.foodonate {
    namespace account {
      namespace userDevelopment {
        interface com.example.foodonate.account.userDevelopment.UserAPI {
            {abstract} + getUser()
            {abstract} + putUser()
        }
      }
    }
  }
  

  namespace com.example.foodonate {
    namespace account {
      namespace userDevelopment {
        class com.example.foodonate.account.userDevelopment.UserBLL {
            - firstName : String
            - lastName : String
            - password : String
            - phoneNo : String
            - profilePicture : String
            - response : Response<UserResponse>
            + UserBLL()
            + UserBLL()
            + UserBLL()
            + checkGetUser()
            + checkUpdateProfile()
            + returnUser()
        }
      }
    }
  }
  

  namespace com.example.foodonate {
    namespace account {
      namespace userDevelopment {
        class com.example.foodonate.account.userDevelopment.UserResponse {
            - firstName : String
            - lastName : String
            - phoneNo : String
            - profilePicture : String
            + UserResponse()
            + getFirstName()
            + getLastName()
            + getPhoneNo()
            + getProfilePicture()
            + setFirstName()
            + setLastName()
            + setPhoneNo()
            + setProfilePicture()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
