@startuml

title __USERREGISTRATIONDEVELOPMENT's Class Diagram__\n

  namespace com.example.foodonate {
    namespace account {
      namespace userRegistrationDevelopment {
        class com.example.foodonate.account.userRegistrationDevelopment.LoginResponse {
            - firstName : String
            - lastName : String
            - phoneNo : String
            - status : String
            - token : String
            + LoginResponse()
            + LoginResponse()
            + getFirstName()
            + getLastName()
            + getPhoneNo()
            + getStatus()
            + getToken()
            + setFirstName()
            + setLastName()
            + setPhoneNo()
            + setStatus()
            + setToken()
        }
      }
    }
  }
  

  namespace com.example.foodonate {
    namespace account {
      namespace userRegistrationDevelopment {
        class com.example.foodonate.account.userRegistrationDevelopment.RegistrationResponse {
        }
      }
    }
  }
  

  namespace com.example.foodonate {
    namespace account {
      namespace userRegistrationDevelopment {
        interface com.example.foodonate.account.userRegistrationDevelopment.UserRegistrationAPI {
            {abstract} + checkLogin()
            {abstract} + checkRegister()
        }
      }
    }
  }
  

  namespace com.example.foodonate {
    namespace account {
      namespace userRegistrationDevelopment {
        class com.example.foodonate.account.userRegistrationDevelopment.UserRegistrationBLL {
            - firstName : String
            - isSuccess : boolean
            - lastName : String
            - password : String
            - phoneNo : String
            - profilePicture : String
            + UserRegistrationBLL()
            + UserRegistrationBLL()
            + checkLogin()
            + checkRegister()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
